### PR TITLE
Branch sales parser fix

### LINKED ISSUE #89: Increase defensiveness of sales command
With reference to #87, this issue aims to address the defensiveness of the sales command.

### PR DESCRIPTION
**Pull request by sarahchow03**
Fixes #89.

### CODE REVIEW

File: src/main/java/commands/AddSalesCommand.java [hunk 1]
```diff
@@ -42,45 +46,38 @@ public AddSalesCommand(String[] argsAuthorMangaQtyPrice) {
...
+        Integer quantitySold = null;
+        Double unitPrice = null;
         try {
             quantitySold = Integer.parseInt(argsAuthorMangaQtyPrice[QUANTITY_INDEX]);
-            if (quantitySold >= 1000000000) {
-                throw new QuantityTooLargeException();
-            }
+            unitPrice = Double.parseDouble(argsAuthorMangaQtyPrice[PRICE_INDEX]);
         } catch (NumberFormatException e) {
+            throw new TantouException("Pretty sure we taught you how to format those numbers already... Seriously...");
```
Comment (xenthm) [inline src/main/java/commands/AddSalesCommand.java:64]: Very sassy, I like it!

File: src/main/java/exceptions/AuthorDoesNotExistException.java [hunk 2]
```diff
@@ -0,0 +1,12 @@
...
+
+public class AuthorDoesNotExistException extends TantouException {
+    public AuthorDoesNotExistException(String authorName) {
+        super(generateAuthorDoesNotExistMessage(authorName));
+    }
+
+    private static String generateAuthorDoesNotExistMessage(String authorName) {
+        return "Author [" + authorName + "] does not exist! "
+                + "Author needs to exist in our catalog first before adding their sales data!";
+    }
```
Comment (xenthm) [inline src/main/java/exceptions/AuthorDoesNotExistException.java:11]: I appreciate the custom exception for this particular invalid input, but I think we should make this message more generic in case other `Command` classes want to use it.

File: src/main/java/exceptions/MangaDoesNotExistException.java [hunk 3]
```diff
@@ -0,0 +1,12 @@
...
+
+public class MangaDoesNotExistException extends TantouException {
+    public MangaDoesNotExistException(String mangaName) {
+        super(generateMangaDoesNotExistMessage(mangaName));
+    }
+
+    private static String generateMangaDoesNotExistMessage(String mangaName) {
+        return "Manga [" + mangaName + "] does not exist! "
+                + "Manga needs to exist in our catalog first before adding their sales data!";
+    }
```
Comment (xenthm) [inline src/main/java/exceptions/MangaDoesNotExistException.java:11]: See above comment:
>I appreciate the custom exception for this particular invalid input, but I think we should make this message more generic in case other Command classes want to use it.

File: src/main/java/parser/Parser.java [hunk 4]
```diff
@@ -181,54 +177,71 @@ private String removeSalesPrefix(String userInput) {
...
-        int indexOfQuantity = userInput.indexOf(QUANTITY_OPTION_REGEX);
-        int indexOfPrice = userInput.indexOf(PRICE_OPTION_REGEX);
+        AuthorArgumentFinder authorArgumentFinder = new AuthorArgumentFinder();
+        MangaArgumentFinder mangaArgumentFinder = new MangaArgumentFinder();
+        PriceArgumentFinder priceArgumentFinder = new PriceArgumentFinder();
+        QuantityArgumentFinder quantityArgumentFinder = new QuantityArgumentFinder();
+
+        ArgumentResult authorResult = authorArgumentFinder.getArgumentResult(userInput);
+        authorName = authorResult.getArgument();
+        String userInputPostAuthorExtraction = authorResult.getOutputString();
```
Comment (xenthm) [inline src/main/java/parser/Parser.java:209]: Great job integrating the new regex parsing method!

File: src/main/java/sales/Sale.java [hunk 5]
```diff
@@ -7,9 +7,8 @@
  * including the quantity sold, the unit price, and the total revenue generated.
  */
 public class Sale {
-    private int quantitySold;
-    private double unitPrice;
-    private double totalRevenue;
+    private Integer quantitySold;
+    private Double unitPrice;
```
Comment (xenthm) [inline src/main/java/sales/Sale.java:11]: Great job changing the implementation of the Sale class! We can now assign `null` values to perform checks to display more details to the user!

File: src/test/java/commands/AddSalesCommandTest.java
Comment (xenthm) [inline src/test/java/commands/AddSalesCommandTest.java:1]: Great job updating the JUnit tests! 🚀 💯 💯 👌

**Review by xenthm — APPROVED** [review]
LGTM! Just a minor issue with custom exception messages in the comments which might affect future development.

File: src/main/java/exceptions/AuthorDoesNotExistException.java (hunk 2 above)
Comment (xenthm) [reply src/main/java/exceptions/AuthorDoesNotExistException.java:11]: Fixed in #106

File: src/main/java/exceptions/MangaDoesNotExistException.java (hunk 3 above)
Comment (xenthm) [reply src/main/java/exceptions/MangaDoesNotExistException.java:11]: Fixed in #106
